apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-hello-http
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads
    repoURL: https://github.com/etiennep/k8s-go-hello-http
    targetRevision: HEAD
  syncPolicy:
    automated: {}
